[package]
name = "devpanel"
version = "0.5.8"
edition = "2024"
description = "Local development environment manager for Debian/Ubuntu"
authors = ["Giannis Smyrnis <smyrnisgiannis@gmail.com>"]

[[bin]]
name = "devpanel"
path = "src/main.rs"

#
#   cargo build                          → dev / dry-run mode (default)
#   cargo build --features production    → real commands, file writes enabled
#   cargo deb                            → always builds with production
#
# default : is the dry-run mode / dev mode , it runs no command that can ruing the developers system config
# production : enables real sudo, apt, systemctl, and file writes
[features]
default    = []
production = []

[package.metadata.deb]
maintainer = "Giannis Smyrnis <smyrnisgiannis@gmail.com>"
copyright = "2025 Giannis Smyrnis"
license-file = ["LICENSE"]
extended-description = """
DevPanel is a desktop GUI for managing your local development environment.
Control Apache, MySQL and PHP services, create Apache VirtualHosts,
and manage SSH keys — all from a single polished interface.
"""
depends = "$auto"
section = "devel"
priority = "optional"
assets = [
  ["target/release/devpanel",          "usr/bin/",                        "755"],
  ["icon.png",                         "usr/share/pixmaps/devpanel.png",  "644"],
  ["devpanel.desktop",                 "usr/share/applications/",         "644"],
  ["share/index.php",                  "usr/share/devpanel/",             "644"],
  ["scripts/devpanel-setup.sh",        "usr/share/devpanel/",             "755"],
]
# cargo deb always passes and has the production features.
deb-features = ["production"]
maintainer-scripts = "scripts/"
revision = ""

[dependencies]
iced  = { version = "0.13", features = ["tokio", "image"] }
tokio = { version = "1",    features = ["full"] }
rfd   = "0.15"
image = "0.25"