#!/bin/bash

create_projects_dir() {
    log_step "2/8 - Creating projects directory"
    if [ ! -d "$PROJECTS_DIR" ]; then
        run_cmd "mkdir projects" mkdir -p "$PROJECTS_DIR" \
            && log_ok "Created: $PROJECTS_DIR" \
            || log_err "Failed to create: $PROJECTS_DIR"
    else
        log_info "Already exists: $PROJECTS_DIR"
    fi
    safe_chown "$REAL_USER:www-data" "$PROJECTS_DIR"
    safe_chmod 755 "$PROJECTS_DIR"
}

install_welcome_page() {
    log_step "3/8 - Installing DevPanel welcome page"
    if [ ! -f "$INDEX_PHP_SRC" ]; then
        log_warn "index.php source not found at $INDEX_PHP_SRC"
        return 0
    fi

    run_cmd "copy index.php" cp "$INDEX_PHP_SRC" "$WEBROOT/index.php" \
        && log_ok "Copied: $INDEX_PHP_SRC -> $WEBROOT/index.php" \
        || log_warn "Failed to copy index.php"
    safe_chown root:www-data "$WEBROOT/index.php"
    safe_chmod 644 "$WEBROOT/index.php"
}

write_devpanel_config() {
    log_info "Writing DevPanel configuration"
    if ! run_cmd "mkdir config dir" mkdir -p "$CFG_DIR"; then
        log_err "Failed to create config directory: $CFG_DIR"
        return 0
    fi

    safe_chown -R "$REAL_USER" "$CFG_DIR"
    cat > "$CFG_FILE" << TOML
# DevPanel configuration
# Generated by devpanel-setup.sh on $(date '+%Y-%m-%d %H:%M:%S')

devpanel_conf = "$DEVPANEL_CONF"
hosts_file    = "$DEV_HOSTS_FILE"
projects_dir  = "$PROJECTS_DIR"
TOML
    safe_chown "$REAL_USER" "$CFG_FILE"
    log_ok "Config written: $CFG_FILE"
}

mark_first_run_done() {
    local sentinel="$CFG_DIR/first_run_done"

    log_info "Marking DevPanel first-run setup complete"
    if ! run_cmd "mkdir config dir" mkdir -p "$CFG_DIR"; then
        log_err "Failed to create config directory: $CFG_DIR"
        return 1
    fi

    if printf '1\n' > "$sentinel"; then
        safe_chown "$REAL_USER" "$sentinel"
        safe_chmod 644 "$sentinel"
        log_ok "First-run sentinel written: $sentinel"
    else
        log_err "Failed to write first-run sentinel: $sentinel"
        return 1
    fi
}

ensure_www_data_group() {
    if groups "$REAL_USER" | grep -q www-data; then
        log_info "$REAL_USER is already in www-data group"
        return 0
    fi

    run_cmd "usermod www-data" usermod -aG www-data "$REAL_USER" \
        && log_ok "Added $REAL_USER to www-data group" \
        || log_warn "Failed to add $REAL_USER to www-data group"
}
